version: "3.1"

services:
  db:
    container_name: django_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: django
      POSTGRES_USER: django
      POSTGRES_DB: django
    ports:
      - "5432:5432"