# Generated by Django 3.1.7 on 2021-03-11 15:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('sass', 'Sass'), ('ts', 'Typescript'), ('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('reactNative', 'React Native'), ('ionic', 'Ionic'), ('php', 'PHP'), ('symfony', 'Symfony'), ('laravel', 'Laravel'), ('drupal', 'Drupal'), ('wordpress', 'Wordpress')], max_length=20)),
                ('cv', models.FileField(upload_to='cv/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
