# Generated by Django 3.1.7 on 2021-03-11 16:11

import cv.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20210311_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(upload_to='cv/', validators=[cv.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('sass', 'Sass'), ('ts', 'Typescript'), ('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('reactNative', 'React Native'), ('ionic', 'Ionic'), ('php', 'PHP'), ('symfony', 'Symfony'), ('laravel', 'Laravel'), ('drupal', 'Drupal'), ('wordpress', 'Wordpress')], max_length=200),
        ),
    ]
